name: Repo updated

on:
  workflow_dispatch:

jobs:
  find-latest-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.latest-release.outputs.version }}
    steps:
      - name: Find latest release of content scope scripts
        id: latest-release
        uses: malmstein/github-asana-action@master
        with:
          github-pat: ${{ secrets.GT_DAXMOBILE }}
          github-repository: 'github-asana-action'
          github-org: 'malmstein'
          action: 'get-latest-repo-release'

  process-update:
    name: Create Pull Request in Android repo
    runs-on: ubuntu-latest
    needs: find-latest-version
    env:
      VERSION: ${{needs.find-latest-version.outputs.version}}
    steps:
      - name: Create Asana task when workflow succeeded
        id: create-task
        uses: malmstein/github-asana-action@master
        with:
          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
          asana-project: '1174433894299346'
          asana-section: '1202853880411179'
          asana-task-name: Update content scope scripts to version ${{ env.VERSION }}
          asana-task-description: |
            Content scope scripts have been updated and a PR created.
            
            If tests failed check out https://app.asana.com/0/1202561462274611/1203986899650836/f for further information on what to do next.
            
            See ${{ steps.create-pr.outputs.pull-request-url }}
          action: 'create-asana-task'

      - name: Add Asana task to Android Releases Board Project
        uses: malmstein/github-asana-action@master
        with:
          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
          asana-task-id: ${{ steps.create-task.outputs.taskId }}
          asana-project: '1200163258163052'
          asana-section: '1204804213442892'
          action: 'add-task-asana-project'


