name: Repo updated

on:
  workflow_dispatch:

jobs:
    create-tag:
      name: Create and Push git tag for version
      runs-on: ubuntu-20.04

      steps:
        - name: Prepare fastlane
          run: bundle install

        - name: Use fastlane lane to create and push tagged release
          id: create_git_tag
          run: |
            bundle exec fastlane tag_and_release_version app_version=${{ github.event.inputs.app-version }}

