name: Asana Integration after Pull Request submitted

on:
  pull_request:
    types: [opened, reopened]

jobs:
  validate-pr:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.external }}
    steps:
      - name: Checking Pull Request sender membership
        id: step1
        uses: malmstein/github-asana-action@master
        with:
          github-pat: ${{ secrets.GT_DAXMOBILE }}
          action: 'check-pr-membership'
  process-internal-pr:
    name: Process internal Pull Request
    if: ${{ needs.validate-pr.outputs.output1 == 'false' }}
    runs-on: ubuntu-latest
    needs: validate-pr
    permissions:
      issues: write
    steps:
      - name: Output Internal PR
        env:
          OUTPUT1: ${{needs.validate-pr.outputs.output1}}
        run: echo "$OUTPUT1"
  process-external-pr:
    name: Process external Pull Request
    if: ${{ needs.validate-pr.outputs.output1 == 'true' }}
    runs-on: ubuntu-latest
    needs: validate-pr
    steps:
      - name: Output External PR
        env:
          OUTPUT1: ${{needs.validate-pr.outputs.output1}}
        run: echo "$OUTPUT1"

      - name: Create Asana task in Internal Project
        uses: malmstein/github-asana-action@master
        with:
          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
          asana-project: ${{ secrets.GH_ASANA_ISSUES_PROJECT_ID }}
          action: 'create-asana-pr-task'
