name: Asana Integration after Pull Request submitted

on:
  pull_request:
    types: [opened, reopened]

jobs:
  pr-opened:
    name: Check if Pull Request is valid
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.external }}
    steps:
      - name: Validating Pull Request
        id: step1
        uses: malmstein/github-asana-action@master
        with:
          github-pat: ${{ secrets.GT_DAXMOBILE }}
          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
          action: 'pr-opened'
  add-asana-comment:
    name: Add Comment to Asana Task
    if: ${{ needs.pr-opened.outputs.output1 == 'false' }}
    runs-on: ubuntu-latest
    needs: pr-opened
    permissions:
      issues: write
    steps:
      - name: Checking if Pull Request is external
        env:
          OUTPUT1: ${{needs.pr-opened.outputs.output1}}
        run: echo "$OUTPUT1"

      - name: Add comment in Asana task
        uses: malmstein/github-asana-action@master
        with:
          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
          asana-project: ${{ secrets.GH_ASANA_ISSUES_PROJECT_ID }}
          trigger-phrase: "Task/Issue URL:"
          action: 'add-asana-comment'
  add-to-asana-projects:
    name: Add Task to Release and Internal Asana projects
    if: ${{ needs.pr-opened.outputs.output1 == 'false' }}
    runs-on: ubuntu-latest
    needs: pr-opened
    steps:
      - name: Add to Asana projects
        uses: malmstein/github-asana-action@master
        with:
          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
          asana-projects: |
            1125036528002799
            1192160553314033
          asana-sections: |
            1125036528002799
            1192160553314033
          trigger-phrase: "Task/Issue URL:"
          action: 'add-asana-project'
  create-asana-task:
    name: Create Asana task
    runs-on: ubuntu-latest
    needs: pr-opened
    if: ${{ needs.pr-opened.outputs.output1 == 'true' }}
    uses: malmstein/github-asana-action@master
    with:
      asana-pat: ${{ secrets.GH_ASANA_SECRET }}
      asana-project: ${{ secrets.GH_ASANA_ISSUES_PROJECT_ID }}
      action: 'create-asana-pr-task'
  add-closed-comment:
    name: Add Comment in Closed Pull Request
    if: ${{ needs.pr-opened.outputs.output1 == 'true' }}
    runs-on: ubuntu-latest
    needs: pr-opened
    permissions:
      pull-requests: write
    steps:
      - name: Checking if Pull Request is valid
        env:
          OUTPUT1: ${{needs.pr-opened.outputs.output1}}
        run: echo "$OUTPUT1"

      - name: Read files
        uses: actions/checkout@v2

      - name: Render response template
        id: render_template
        uses: chuhlomin/render-template@v1.7
        with:
          template: .github/pr-reply-template.md

      - name: Add comment to Pull Request
        uses: peter-evans/create-or-update-comment@v3.0.2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: '.github/pr-reply-template.md'