name: Pull Request changed -> Sync Asana PR task

on:
  pull_request_review:
  pull_request:
    types:
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - assigned
      - ready_for_review

concurrency:
  group: ${{ github.ref }}

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4
      - uses: duckduckgo/native-github-asana-sync@feature/david/pr-sync
        with:
          github_pat: ${{ secrets.GT_DAXMOBILE }}
          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
          workspace_id: ${{ vars.GH_ASANA_WORKSPACE_ID }}
          project_id: ${{ vars.GH_ASANA_CODE_REVIEWS_PROJECT_ID }}
          in_progress_section_id: ${{ vars.GH_ASANA_CODE_REVIEWS_IN_PROGRESS_SECTION_ID }}