name: Asana Integration after Pull Request submitted

on:
  pull_request:
    types: [opened, reopened]

jobs:
  add-comment-ddg-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Add Comment to Asana task
        uses: malmstein/github-asana-action@master
        with:
          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
          trigger-phrase: "Task/Issue URL:"
          action: 'add-pr-comment'
  create-task-community-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create Asana Task from Community PR
        uses: malmstein/github-asana-action@master
        with:
          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
          trigger-phrase: "Fixes Issue #:"
          action: 'create-pr-task'