name: Pull Request Reviewed -> Asana Sync

on:
  pull_request_review:
    types: [submitted]

jobs:
  pr-reviewed:
    runs-on: ubuntu-latest
    steps:
      - name: Find Asana Task in PR description
        uses: duckduckgo/native-github-asana-sync@david/improve-pr-notifications
        id: find-asana-task-id
        with:
          action: 'find-asana-task-id'
          trigger-phrase: ${{ inputs.trigger-phrase }}

      - name: Add Approved Comment to Asana Task
        if: github.event.review.state == 'approved'
        uses: duckduckgo/native-github-asana-sync@david/improve-pr-notifications
        id: post-comment-pr-approved
        with:
          action: 'post-comment-asana-task'
          asanta-task-id: '${{ steps.find-asana-task-id.outputs.asanaTaskId }}'
          asanta-task-comment: 'PR: ${{ github.event.pull_request.html_url }} has been approved.'

      - name: Add Changes Requested Comment to Asana Task
        if: github.event.review.state == 'changes_requested'
        uses: duckduckgo/native-github-asana-sync@david/improve-pr-notifications
        id: post-comment-pr-changes-requested
        with:
          action: 'post-comment-asana-task'
          asanta-task-id: '${{ steps.find-asana-task-id.outputs.asanaTaskId }}'
          asanta-task-comment: 'PR: ${{ github.event.pull_request.html_url }} has changed requested.'

      - name: Add Dismissed Comment to Asana Task
        if: github.event.review.state == 'dismissed'
        uses: duckduckgo/native-github-asana-sync@david/improve-pr-notifications
        id: post-comment-pr-dismissed
        with:
          action: 'post-comment-asana-task'
          asanta-task-id: '${{ steps.find-asana-task-id.outputs.asanaTaskId }}'
          asanta-task-comment: 'PR: ${{ github.event.pull_request.html_url }} has been dismissed.'

      - name: Add Review Comment to Asana Task
        if: github.event.review.state == 'commented'
        uses: duckduckgo/native-github-asana-sync@david/improve-pr-notifications
        id: post-comment-pr-reviewed
        with:
          action: 'post-comment-asana-task'
          asanta-task-id: '${{ steps.find-asana-task-id.outputs.asanaTaskId }}'
          asanta-task-comment: 'PR: ${{ github.event.pull_request.html_url }} has been reviewed.'
